### ISSUE TITLE
Assign issues to milestones for release planning

### ISSUE THREAD

**Issue by tdiesler** [ipfs/java-ipfs-api#105]
Could you perhaps please assign open issues to milestones and (if possible) set a due date for the milestone. I'd like to get an idea what still needs to get done until the next version can be released.

A release of what is in master currently, would work for me as well.

cheers
-- thomas

**Comment by ianopolous** [comment]
I work on this for free in my spare time so it mainly depends when I can find time. I'm happy to do a release now as there several important changes.
