### ISSUE TITLE
Latest tag uses a snapshot version

### ISSUE THREAD

**Issue by tdiesler** [ipfs/java-ipfs-api#107]
To fix this issue, you can do 

```
git tag -d v1.2.2
git push origin :v1.2.2
mvn release:prepare
git push origin master
git reset --hard
```

1. deletes the local tag
2. deletes the remote tag
3. interactively updates the version in the pom, creates the tag, and pushes the tag upstream
4. also push the latest master, which 3 does not do (I think)
5. remove the release tmp files, which otherwise `mvn release:perform` would do

A tag that points to a snapshot is not usable in maven.

In future it might be a good idea to setup the pom properly such that 

```
mvn release:prepare
mvn release:perform
```

works. I can unfortunately not do that for you, because it would require write access to the git repo for testing.

**Comment by ianopolous** [comment]
I don't want maven installed, but I'll see if I can fix it.

**Comment by ianopolous** [comment]
How is it now?

**Comment by tdiesler** [comment]
Yes, this can be closed
