### ISSUE TITLE
unit test is not pass

### ISSUE THREAD

**Issue by zuccbug** [ipfs/java-ipfs-api#11]
enviroment: jdk 1.8, windows 7, ipfs 0.4.2
there are 5 tests not pass,they are  refsTest, pinTest, singleFileTest, fileContentsTest, hostFileTest

**Comment by zuccbug** [comment]
i debug it ,foud that JSONParser.parse 's call failed ,because the parameter was not json string ,why use JSONParser to parse them ? i didn't found there had some json string

**Comment by ianopolous** [comment]
The tests are all passing against the current head of go-ipfs. You would see exactly those failures if you were running against a previous version of ipfs. Are you sure you don't have two versions of ipfs installed?

**Comment by zuccbug** [comment]
public List<MerkleNode> add(List<NamedStreamable> files) throws IOException {
        Multipart m = new Multipart("http://" + host + ":" + port + version+"add?stream-channels=true", "UTF-8");
        for (NamedStreamable f : files)
            m.addFilePart("file", f);
        String res = m.finish();
        return JSONParser.parseStream(res).stream()
//                .skip(1)
                .map(x -> MerkleNode.fromJSON((Map<String, Object>) x))
                .collect(Collectors.toList());
    }

**Comment by zuccbug** [comment]
why  ".skip(1) " ?

**Comment by zuccbug** [comment]
i run the test case singleFileTest() failed because of the code " .skip(1)" in the method "add". list range checked failed.

**Comment by ianopolous** [comment]
Try updating java-ipfs-api from git and try it again. I've added an explicit minimum version check on IPFS.

**Comment by zuccbug** [comment]
ok,i will try it

**Comment by zuccbug** [comment]
i clone the code of recent version.and tried it ,there are also have 5 failed testcase

**Comment by zuccbug** [comment]
i'm make sure the ipfs's version is 0.4.2

**Comment by zuccbug** [comment]
fail reason of the test case "refsTest" is that , String jsonStream = new String(retrieve("refs/local")); ,because the jsonStream is not json string in fact .is normal string of peer's id(hash code in multilines, one hash per line)

**Comment by zuccbug** [comment]
fail reason of the test cast "pinTest" is that , JSONParser.parseStream(res).stream().skip(1)........i found that while " .skip(1)" called , the result is null.

**Comment by ianopolous** [comment]
In previous versions of IPFS those tests will fail for exactly those reasons. The format changed from just strings to JSON in the latest IPFS. I can't reproduce any of these failures. Is your IPFS built from source? what does "ipfs version" return?

**Comment by zuccbug** [comment]
my ipfs is not built from source . "ipfs version " return "ipfs version 0.4.2"

**Comment by zuccbug** [comment]
i download it from " https://ipfs.io/ipns/dist.ipfs.io/#go-ipfs"

**Comment by ianopolous** [comment]
Can you try with an IPFS built from source? It sounds like they need to bump the version again.

**Comment by zuccbug** [comment]
ok, i will build it from source.and try it again

**Comment by zuccbug** [comment]
I tried to build go-ipfs from src,the version0.4.2, the test case all pass..thank you

**Comment by ianopolous** [comment]
Cool. As soon as the go-ipfs version is increased I will increase our min version.
