### ISSUE TITLE
Modularize java-multiaddr and move it to multiformats

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/java-ipfs-api#12]
I would like to have multiaddr moved into it's own module (or package, or whatever you call it in Java), and moved to the multiformats organization. Is this feasible? 

Tracking issue: https://github.com/multiformats/multiformats/issues/4

**Comment by RichardLitt** [comment]
Not demanding! I'm just curious if this is possible or not. It would be great if we could have all of the multiformat implementations together.

**Comment by ianopolous** [comment]
Yep, originally it was simpler to just have a single jar, especially given there's only 10 files, but it does make sense to separate out if we plan on implementing a Java implementation of IPFS itself (which we do). I will do this as soon as I get a chance.

**Comment by RichardLitt** [comment]
Oh, awesome! Thanks @ianopolous!

**Comment by theobat** [comment]
Hey, @ianopolous, I can deal with this if you want, I could create two different additional "libraries" in this repo for now, one being Multibase and the other being Multiaddress ?

**Comment by ianopolous** [comment]
G'day @theobat. I am actually hoping to get to it this Sunday, but thank you for the offer.
