### ISSUE TITLE
cant instantiate IPFS ipfs = new IPFS("/ip4/127.0.0.0/tcp/5001")

### ISSUE THREAD

**Issue by amrouchk** [ipfs/java-ipfs-api#120]
sorry if this is too basic but I couldnt run the example shown in  readme. 
I tried this IPFS ipfs = new IPFS("/ip4/127.0.0.1/tcp/5001"); with this ipfs.refs.local();
but it doesnt work
also this one doesnt work with me
    @Test
    public void connection() throws IOException {
        IPFS ipfs = new IPFS("/dnsaddr/ipfs.infura.io/tcp/5001/https");
        System.out.println("connected");
        System.out.println("id: " + ipfs.id());
    }
I installed ipfs-go and the daemon is running so everything seems good
Any helps?? appreciates 
![1](https://user-images.githubusercontent.com/8835624/49165871-260a6380-f36d-11e8-95d3-cd00eb5afc7a.png)
![2](https://user-images.githubusercontent.com/8835624/49165873-260a6380-f36d-11e8-9b64-5c6f15f85d79.png)
![screenshot from 2018-11-29 00-22-26](https://user-images.githubusercontent.com/8835624/49165874-273b9080-f36d-11e8-924d-8a840e645f8a.png)

_Originally posted by @amrouchk in https://github.com/ipfs/java-ipfs-api/issues/115#issuecomment-442507207_

**Comment by amrouchk** [comment]
The problem has solved by  importing the librarries, multiaddress, multibase, multihash 
regards

**Comment by RISHABHAGRAWALZRA** [comment]
I am also facing the same issue. Pls help
Actually i added the dependency ('implementation group: 'com.github.ipfs', name: 'java-ipfs-http-client', version: 'v1.3.3'') in app.gradle file and synced properly.
but when i try to use any method in app its not recognising it and also the import statements 
![Screenshot from 2021-08-02 11-59-06](https://user-images.githubusercontent.com/43982251/127814093-83d81d81-06ef-4d6f-b50f-10d5cab02618.png)
![Screenshot from 2021-08-02 12-02-08](https://user-images.githubusercontent.com/43982251/127814290-0f5bff7c-c129-4974-9f0f-e6af49ae6865.png)

Thanks
