### ISSUE TITLE
Unable to add file to IPFS using add method

### ISSUE THREAD

**Issue by adrian-git-hub-user** [ipfs/java-ipfs-api#14]
I'm using IPFS version 0.4.2 and have cloned branch 0.4.2 . Using this code : 

```
package org.ipfs.api;
import java.io.*;

public class Main {
public static void main(String args[]) throws Exception{

	IPFS m = new IPFS("myhost" , 8080);
	NamedStreamable.ByteArrayWrapper file = new     NamedStreamable.ByteArrayWrapper("hello.txt", "G'day world! IPFS rocks!".getBytes());

try {
		System.out.println(m.add(file));
       } catch (IOException e) {

       e.printStackTrace();  
        }
}
}


```produces error : 

java.io.IOException: Server returned status: 404 with body:  and Trailer header: null
	at org.ipfs.api.Multipart.finish(Multipart.java:106)
	at org.ipfs.api.IPFS.add(IPFS.java:64)
	at org.ipfs.api.IPFS.add(IPFS.java:52)
	at org.ipfs.api.Main.main(Main.java:16)



This should work as is ? Or am I missing something ?

**Comment by ianopolous** [comment]
There was a breaking API change in ipfs 0.4.3. Are you building from source or using the release jar?

**Comment by adrian-git-hub-user** [comment]
@ianopolous I built 0.4.2 from source

**Comment by ianopolous** [comment]
Are you able to use >= 0.4.3 ipfs and the latest master of this lib? I need to do another release.

**Comment by Kubuxu** [comment]
@ianopolous is it possible to add compatibility clause there in a `catch` statement or similar? I know it will be additional work but it seems to be a frequent pain point.

**Comment by adrian-git-hub-user** [comment]
@ianopolous I'm constrained to use the latest official release. Perhaps can provide a maven release version instead of snapshot to match the latest ipfs release, just a suggestion. This library is appreciated and I will visit it again once ipfs release an official version this library is compatible with.

**Comment by ianopolous** [comment]
@Kubuxu There is a version enforcer in the latest master, but not in the last release. I will do another release this weekend.

**Comment by Kubuxu** [comment]
@adrian-git-hub-user: there is release that is compatible with the lib https://dist.ipfs.io/go-ipfs/v0.4.3-rc3

**Comment by ianopolous** [comment]
@adrian-git-hub-user I've pushed a new release which is compatible with ipfs 0.4.3-rc3
