### ISSUE TITLE
Adding a folder throws a FileNotFound Exception

### ISSUE THREAD

**Issue by NickGeek** [ipfs/java-ipfs-api#15]
If you pass a NamedStreamable.FileWrapper that is a wrapping around a folder, ipfs.add throws a FileNotFound exception.

**Comment by ianopolous** [comment]
At the time of writing, there wasn't an API for adding a directory, but now there is (the files api) so I will update this soon.

**Comment by NickGeek** [comment]
Thanks.

**Comment by NickGeek** [comment]
@ianopolous Is there any update on a fix?

**Comment by ianopolous** [comment]
Hi Nick, Sorry I haven't finished this yet. It turns out it was less documented than I'd hoped, and as this isn't my day job, I'm restricted to working on it in the evenings. I am actively working on it though.

**Comment by ianopolous** [comment]
Ok that's implemented now in master. In the end I didn't need the new files api.
