### ISSUE TITLE
dependencies included in the distribution

### ISSUE THREAD

**Issue by magwas** [ipfs/java-ipfs-api#19]
having binary blobs which are outputs of other projects is not good.
the transition could be made in the following way:
1) document which dependency is obtained from where
 my guesses:
   multiaddr.jar  multibase.jar  multihash.jar: https://github.com/multiformats
   hamcrest-core-1.3.jar  junit-4.12.jar: maven repo
   cid.jar: ??? I have found only https://github.com/ipfs/go-cid
2) modify pom.xml to obtain the dependencies in compile time (and build.xml, but actually you should delete it)
3) delete the lib folder
4) nudge multiformats to be good citizens and publish in maven. update pom.xm when done
You should also publish in maven, but that's another issue.
If you do 1), i might do 2) for you.

**Comment by ianopolous** [comment]
I'm of the view that depending on a third party outside your source tree to be able to compile your project is a bad idea. As soon as that third party is unavailable, you cannot progress. I'm fine with the maven version here doing what it wants (including getting dependencies from a third party), but the ant version, which I use, will continue to vendor it's dependencies into the lib directory. This means that all you need to be able to build and run the project is a checkout of this repository. You are right that the sources should be more documented. Cid is from https://github.com/ipld/java-cid

**Comment by ianopolous** [comment]
I've updated the dependency list in the readme

**Comment by magwas** [comment]
Thank you. Now it's my turn, so I won't close the ticket just yet. Feel free to nudge me if nothing happens.
There are some fundamental differences between the maven and the node.js repository :)
I believe one can count on that once something is in maven, that will stay there.
You have no choice but to stay on the shoulder on others. Your project have a lot of dependencies from the system c library to each of the build tools. Why single out source code dependencies?
All you have to do is to make sure that you are building on solid foundations.

**Comment by ianopolous** [comment]
I do not know the owners of the maven central repository and do not want to rely on them staying around. I also want to be able to do a fresh git clone and then have everything I need to build locally, so I should be able to proceed even if I'm offline after the clone.
