### ISSUE TITLE
Inner classes of IPFS are not public

### ISSUE THREAD

**Issue by gamemanj** [ipfs/java-ipfs-api#2]
The inner classes of the IPFS object aren't public, so they can't be accessed from outside the org.ipfs package.
My current workaround is to put code interfacing with those parts in a class in org.ipfs, but that's not exactly a good solution...

Here's an example of the kind of error, given from attempting 
```java
    IPFS myself = new IPFS("/ip4/127.0.0.1/tcp/5001");
    myself.name.resolve(Multihash.fromBase58("QmarsUDwQ5ak34KU6xJbr2iMuatB7e69WfuSjEBG3v7zvu"));
```
`Error:(18, 20) java: resolve(org.ipfs.Multihash) in org.ipfs.IPFS.Name is defined in an inaccessible class or interface`
I'm using OpenJDK, javac -version reports "javac 1.8.0_65".
If IDE matters (it shouldn't, given these are compiler errors, but still), i'm using JetBrains IDEA Community Edition.

**Comment by ianopolous** [comment]
Thank you. The accessibility has been fixed, and included in a new release.
