### ISSUE TITLE
Api structure

### ISSUE THREAD

**Issue by magwas** [ipfs/java-ipfs-api#24]
The html API looks like as it is because the technology (REST) used.
And even that api shows that its designers did think in an object-oriented way.
I believe doing things like this would be more natural:

    @Test
    public void we_can_add_a_link_to_an_object() throws IOException {
    	IPFSObject myOldObj = IPFSObject.getMyObj(ipfs);
    	IPFSObject myNewObj = new IPFSObject(ipfs);
    	myNewObj.addLink("next", myOldObj);
    	assertEquals(myOldObj, myNewObj.getLinked("next"));
    }

I am in the process of creating such an api as a side effect of one of my project. Currently it uses java-ipfs-api as a low level api. However I believe that there are things which should be remediated there as well (173 warnings in a single project, and more than 10 classes in a single file are sure signs of it), and I am not even convinced that having the low-level api is a good idea in the first place.
I would be happy to discuss it.

**Comment by ianopolous** [comment]
I'm very happy to consider any PRs. This is meant to be a very thin wrapper around the http api though.
