### ISSUE TITLE
Implement Java API in servlet

### ISSUE THREAD

**Issue by riyazlafir** [ipfs/java-ipfs-api#26]
Hi All,
I want to know how to use java-ipfs-api with servlet page ? is there are any example code available for this ? how can I do this ?

**Comment by ianopolous** [comment]
G'day riyazlafir, 
I've never used it in a servlet, just in a standalone application, so do let us know how you get on. Sorry we can't be more helpful. 
Cheers,
Ian

**Comment by whtech** [comment]
I think you can initial a singleton instance to start spread the files.
