### ISSUE TITLE
Pubsub API

### ISSUE THREAD

**Issue by mariosk** [ipfs/java-ipfs-api#32]
Any plans to support the pubsub API in Java?

**Comment by ianopolous** [comment]
Yes, in my, hopefully very soon, update I'll add all the new calls.

**Comment by mariosk** [comment]
Thanks a lot Ian. If you want I can help towards this effort, so that we can have them as soon as possible.

**Comment by mariosk** [comment]
@ianopolous do we have update on the issue?

**Comment by ianopolous** [comment]
I've just pushed a commit to master that implements all the pubsub calls. Be aware that it is an experimental api and likely to change though. Also, the pub command doesn't work yet.

**Comment by ianopolous** [comment]
Pub is working now also.

**Comment by mariosk** [comment]
Thanks a lot @ianopolous, I'll check it out tomorrow and let you know how it goes.

**Comment by mariosk** [comment]
@ianopolous it seems that the latest changes with pubsub maybe have broken the ipfs.add() functionality. Could you please take a look at issue 10?

**Comment by ianopolous** [comment]
Should be fine now. Let me know how you get on.

**Comment by mariosk** [comment]
Thanks again @ianopolous, just keeping a note here that one should run the ipfs daemon with:
$ ipfs daemon  --enable-pubsub-experiment

in order to enable the pubsub API.

**Comment by mariosk** [comment]
@ianopolous just did some tests and still having issues to make it run. I'm running only the pubsub test case and I get no response from IPFS at the following call (it blocks there):

        Object first = sub.get();

Could you please try to run only pubsub test case and let me know what it reports to you?

**Comment by ianopolous** [comment]
the pubsub test runs fine for me. sub.get() will block until something has been published to that topic (as well as an empty object at first it seems).

**Comment by mariosk** [comment]
Great, so something is related to my setup. I've launched the daemon like:
mkara@DELLMK MINGW64 ~
$ ipfs daemon --enable-pubsub-experiment
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.12.28/tcp/4001
Swarm listening on /ip4/169.254.157.170/tcp/4001
Swarm listening on /ip4/169.254.237.30/tcp/4001
Swarm listening on /ip4/192.168.10.1/tcp/4001
Swarm listening on /ip4/192.168.11.164/tcp/4001
Swarm listening on /ip4/192.168.153.1/tcp/4001
Swarm listening on /ip6/2001:0:9d38:90d7:dc:1496:b094:9727/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

What am I doing wrong? Any ideas how to debug?

**Comment by mariosk** [comment]
OK just found that it is related to the operating system. In my VM linux works fine, but not in windows (used powershell, git bash and simple cmd shell with the same results).

**Comment by mariosk** [comment]
Another interesting thing is that when I press Ctrl-C (and eventually shutdown) the ipfs-daemon (in windows) I can see the message coming to the subscriber process normal.

**Comment by ianopolous** [comment]
Hmm that's weird. As you say, it shouldn't be an issue with the Java api, and it sounds like an issue with ipfs itself. You could try submitting an issue on go-ipfs? Do you have issues with any other commands on windows using the cmd?

**Comment by ianopolous** [comment]
My guess is it is Go not being cross platform properly, but that's just a guess.

**Comment by mariosk** [comment]
Yes what you say makes sense. I'll try to debug it more and if I can't find another clue I'll submit an issue to go-ipfs, thanks!

**Comment by mariosk** [comment]
@ianopolous I've moved to Linux in order to continue my work. One question: Why the assertion you made in pubsub method, checks against an empty collections map? Should it have a message, since one line above there is a publish message?

**Comment by ianopolous** [comment]
The protocol isn't standardized yet. That's just what the current ipfs implementation seems to do (send an empty object as the first thing in the sub stream).

**Comment by ianopolous** [comment]
I've updated the test to retrieve after the pub as well.

**Comment by alvin-reyes** [comment]
Any updates on the Windows? I'm also encountering the same issue on my Windows Machine.
