### ISSUE TITLE
Trying to use with android studio error

### ISSUE THREAD

**Issue by BenKrarup** [ipfs/java-ipfs-api#35]
Hi,

Sorry if this is stupid but I am getting an error - "Error:(39, 21) error: cannot access MultiAddress
class file for io.ipfs.multiaddr.MultiAddress not found" when using - 
IPFS ipfs = new IPFS("/ip4/127.0.0.1/tcp/5001");

I have included the jar file in the project, I just want to be able to upload and read files from IPFS. Any help would be great.

Cheers!

**Comment by BenKrarup** [comment]
Hi, sorry I have fixed this issue now and the build runs successfully but on - IPFS ipfs = new IPFS("/ip4/127.0.0.1/tcp/5001"); 
It just hangs forever, any idea?

Thanks!

**Comment by mariosk** [comment]
@BenKrarup I guess the problem is that you don't run an IPFS daemon locally that's why you're getting hang forever. I'd start from IPFSdroid, as far as I can see it runs an IPFS daemon inside android.

**Comment by BenKrarup** [comment]
@mariosk Hi, I actually solved the problem just now - for some reason it throws android.os.NetworkOnMainThreadException but wasn't actually showing me that exception just hanging. https://stackoverflow.com/questions/6343166/how-do-i-fix-android-os-networkonmainthreadexception this fixed the error for any one else that has this problem. Also I think IPFSdroid is an actual app for accessing IPFS on android rather than an API for android studio which I need as I'm making a DApp. Could be wrong though.

Cheers!

**Comment by mariosk** [comment]
@BenKrarup great! So this issue should be closed, right?

**Comment by BenKrarup** [comment]
@mariosk Please, yeah.

**Comment by IfhamPain** [comment]
@BenKrarup I am getting the error "error: cannot access MultiAddress
class file for io.ipfs.multiaddr.MultiAddress not found" 

Can you state how did you solve this?
