### ISSUE TITLE
Android SDK 25 and Lower Fix for java.nio.file

### ISSUE THREAD

**Issue by BenKrarup** [ipfs/java-ipfs-api#37]
Hi,

I have made a few changes just to get rid of java.nio.file because it is not supported lower than android SDK 26 (o). It was very quick and I haven't really tested it but it seems to be working. If anyone wants to see it just comment. 

Cheers.

**Comment by ianopolous** [comment]
This is primarily a Java api, so we will be using relatively recent java features. Personally I would use a kotlin api for android development. Though do feel free to fork and apply android specific fixes.
