### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by celeduc** [ipfs/java-ipfs-api#39]
Could someone with Travis admin access please activate https://travis-ci.org/ipfs/java-ipfs-api ?

**Comment by ianopolous** [comment]
ping @diasdavid, could we get this enabled please?

**Comment by VictorBjelkholm** [comment]
@ianopolous activated TravisCI for you but as a FYI, we're moving all CI to Jenkins instead of Travis/Circle. But as of now, Travis has been activated for this repository.

**Comment by ianopolous** [comment]
Thanks @VictorBjelkholm !
