### ISSUE TITLE
Incorrect api call in Pubsub.pub()

### ISSUE THREAD

**Issue by lbelyaev** [ipfs/java-ipfs-api#43]
Hi,
looks like the current lines #236-238 in IPFS.java should read:
**`        public Object pub(String topic, String data) throws IOException {
            return IPFS.this.retrieveAndParse("pubsub/pub?arg="+topic + "&arg=" + data);
        }
`**
instead of
`        public Object pub(String topic, String data) throws IOException {
            return IPFS.this.retrieveAndParse("pubsub/peers?arg=" + topic + "&arg=" + data);
        }
`
Cheers

**Comment by ianopolous** [comment]
Thanks for finding that! That's fixed in master now.
