### ISSUE TITLE
MerkleNode.class : ClassCastException (go-ipfs:v0.4.11)

### ISSUE THREAD

**Issue by raucoule1u** [ipfs/java-ipfs-api#44]
Since the version v0.4.11 of the IPFS client, I got an error in the Merklenode.class file.
The error is a ClassCastException on the following piece of code (lines 69-75).

```
     if (json.containsKey("Size")) {
        Optional.empty();
        var10000 = Optional.of((Integer)json.get("Size"));
      } else {
        Optional.empty();
        var10000 = Optional.empty();
      }
```

The ClassCastException indicates that `(Integer)json.get("Size")` is a String and cannot be cast to Integer.

**Comment by ianopolous** [comment]
This is fixed in master. I will do a release soon.
