### ISSUE TITLE
ipfs.id()

### ISSUE THREAD

**Issue by Restaldt** [ipfs/java-ipfs-api#50]
Not too much of an issue but here we go:

So running ipfs id in the command prompt/terminal prints out my local ipfs id/public key but when running ipfs.id() in java it throws an error because the function expects a string. Sending it a blank string (ipfs.id("")) just causes it to fail to find that blank id instead of returning my local information.

Is there any particular reason why we cant use this function to get our local information? 

Am i missing something and doing this wrong? 

id command description from the Commands | IPFS Docs:

DESCRIPTION

  Prints out information about the specified peer.
  If no peer is specified, prints out information for local peers.

 'ipfs id' supports the format option for output with the following keys:
  <id> : The peers id.
  <aver>: Agent version.
  <pver>: Protocol version.
  <pubkey>: Public key.
  <addrs>: Addresses (newline delimited).

  EXAMPLE:

      ipfs id Qmece2RkXhsKe5CRooNisBTh4SK119KrXXGmoK6V3kb8aH -f="<addrs>\n"

**Comment by ianopolous** [comment]
Good catch! I've just pushed an implementation of a 0 arg id call.

**Comment by Restaldt** [comment]
🖒
