### ISSUE TITLE
ipfs.dht.findpeer()

### ISSUE THREAD

**Issue by Restaldt** [ipfs/java-ipfs-api#51]
Not actually sure if this is an issue or not but i figured it bring it up anyways:

ipfs.dht.findpeer() currently expects a MultiAddress when the CL version expects a peerID:

from the Commands | IPFS Docs:

ipfs dht findpeer

USAGE
  ipfs dht findpeer <peerID>... - Query the DHT for all of the multiaddresses associated with a Peer ID.

SYNOPSIS
  ipfs dht findpeer [--verbose | -v] [--] <peerID>...

ARGUMENTS

  <peerID>... - The ID of the peer to search for.

OPTIONS

  -v, --verbose bool - Print extra information. Default: false.

DESCRIPTION

  Outputs a list of newline-delimited multiaddresses.

Shouldn't this function take in a MultiHash namely the peerID that you are trying to "find"?

**Comment by ianopolous** [comment]
Thanks for finding this. I'm pushing a fix now.

**Comment by Restaldt** [comment]
🖒
