### ISSUE TITLE
pubsub has very high latency

### ISSUE THREAD

**Issue by klausmyrseth** [ipfs/java-ipfs-api#55]
I was testing the simplest form of pub/sub with the java api.

on localhost I experience 250-300 milliseconds latency on message, while when I use the go tools, its down to just a few milliseconds. Is there a way to get low latency for the java implementation as well?

**Comment by ianopolous** [comment]
I was waiting for the api to stabilise before investing any real time in it. But maybe that time has come.

**Comment by ianopolous** [comment]
After a quick glance it's almost certainly the thread pool usage. Can you show me your code?

**Comment by ianopolous** [comment]
One possibility is I could add a version that consumes the calling thread, and just blocks for transmissions.

**Comment by ianopolous** [comment]
I've just pushed a commit that adds a synchronous version to master, and a test that demonstrates it. This takes ~1ms for a pub and the receiving sub.

**Comment by klausmyrseth** [comment]
Awsome :) ill test it out. Is planning to make an agent network based on pubsub so will be testing it quite extensively in the future!

**Comment by klausmyrseth** [comment]
Using your code I wrote a scenario to not pubsub within the same code, but to see how its through ipfs when pub is from one source and sub from another.

Its much faster then your previous edition. Is it possible to get the templating to to Map instead of Object?

Also it would be nice being able to make an observer on the sub instead of polling it, just for making super clean code.

Following consumer code:
```
        ConcurrentLinkedQueue<Object> res = new ConcurrentLinkedQueue<>();
        new Thread(() -> {
            try {
                ipfs.pubsub.sub("demo", res::add);
            } catch (IOException e) {
                throw new RuntimeException(e);}
        }).start();

        while (true) { // Bear with me its just a test :D
            if (res.size() > 0) {
                Map msg = (Map) res.poll();
                if (msg.size() > 0) {
                    String from = msg.get("from").toString();
                    String topicId = msg.get("topicIDs").toString();
                    String seqno = msg.get("seqno").toString();
                    String data = new String(Base64.decodeBase64(msg.get("data").toString()));
                    LOG.debug("Received [{}]-[{}] {}) {}.",
                            from,
                            topicId,
                            seqno,
                            data);
                }
            }
        }
```

and my producer:
```
#!/bin/bash

for i in {1..100}
do
  ipfs pubsub pub demo "Test $i"
done
```

Result cut a few lines of output:
05:31:54.890 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58Om9w93E=) Test 88.
05:31:54.944 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58OnKuOP4=) Test 89.
05:31:54.997 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58OnXQhuc=) Test 90.
05:31:55.047 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58OnjIIE4=) Test 91.
05:31:55.110 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58OnyT4kw=) Test 92.
05:31:55.164 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58On/GKkM=) Test 93.
05:31:55.214 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58OoK9i/o=) Test 94.
05:31:55.308 [main] DEBUG t.s.b.s.b.agent.Main - Received [EiASrFX2HISmTYWpA6+QExuuADxmXdhzDB4GynQxK2nSBA==]-[[demo]] FQ58OohcEDA=) Test 95.

**Comment by ianopolous** [comment]
I've just pushed a commit to make sub return Map. For the remaining things I'd like to keep this api stateless, and adding anything like registerConsumer would break that. The data type is actually url-encoded (it's sent in the url string), so it's not just random bytes.

**Comment by cybershrapnel** [comment]
oooo, sounds like I need to go through the new updates... I have an older version built into the nanocheeze app and I bypassed some of it's functionality and just use the http proxy as a workaround for some things....
