### ISSUE TITLE
Question：How I generate Cid before data stored?

### ISSUE THREAD

**Issue by HanawaBanana** [ipfs/java-ipfs-api#64]
I know the java-ipfs-api just invoke ipfs server.
But now I want to get Cid of byte[] before invoke, I tried java-cid. But the Cid of java-ipfs-api is different from the Cid of java-cid(version 0). 

this is my code.
```java
        String ss = "123321";
        // 数据存储IPFS逻辑
        try {
            IPFS ipfs = new IPFS(Constants.IPFS_URL);//    "/ip4/0.0.0.0/tcp/5001"
            ipfs.refs.local();

            NamedStreamable.ByteArrayWrapper file = new NamedStreamable.ByteArrayWrapper(ss.getBytes());
            MerkleNode addResult = ipfs.add(file).get(0);
            if (null != addResult && null != addResult.hash) {
                System.out.println(addResult.hash.toString());
            }
            MessageDigest hasher = MessageDigest.getInstance("SHA-256");
            byte[] hash = hasher.digest(ss.getBytes());
            Multihash mhash = new Multihash(Multihash.Type.sha2_256, hash);
            Cid cid = Cid.buildCidV0(mhash);
            System.out.println(cid.toString());
        } catch (IOException | IllegalArgumentException | NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
```

I get different result.

```
QmZE8aUxitmPdBjriC82rhhUmQbeh7KP4oEbgqBEATMct5
QmZKRiNkuVutGrvxWDr6dhp5zJa7sBM5HPWhuWF2mZgScm
```

Why? I doubt it maybe the ipfs server not only SHA256 byte[], but also other operation.

If anyone give advices. Thanks a lot!

**Comment by HanawaBanana** [comment]
How do I to get the same hash by using java method?
or How do I get the unixfs data structure byte[]?

**Comment by ianopolous** [comment]
The short answer is you can't using the add command. Why do you need it in advance?

If your data is smaller than 256 KiB you can use the block.put command which doesn't do any wrapping. But you will need to use format "raw".

**Comment by HanawaBanana** [comment]
Because I need use cid without ipfs service.
Now I solved it.
I Extracted the library files, Write it a shell script.
Thanks your reply:)

**Comment by ianopolous** [comment]
In general you would need to implement the same chunking algorithm (rabin), encoding (protobufs) and data structures (unixfs) that ipfs uses internally.

**Comment by rmnvalera** [comment]
i have created a module which can generate the correct file hash:
https://github.com/rmnvalera/java-cid-generate-hash
