### ISSUE TITLE
PubSub API

### ISSUE THREAD

**Issue by abueide** [ipfs/java-ipfs-api#73]
Could some one explain how I'm supposed to properly use the subscribe part of the pubsub api? I'm new to multithreading and concurrency and I'm finding it really confusing. I'm using scala right now, but any java examples would be a huge help!

Thank you in advance

**Comment by ianopolous** [comment]
Hi! It's still a work in progress, but you can look at the tests for it:
https://github.com/ipfs/java-ipfs-api/blob/master/src/test/java/io/ipfs/api/APITest.java#L410
