### ISSUE TITLE
How to judge Multihash is a file or a directory

### ISSUE THREAD

**Issue by AndyYang2014** [ipfs/java-ipfs-api#83]

**Comment by Stebalien** [comment]
Just to make sure we get the terminology correct: The `QmId` in `/ipfs/QmId` is a "CID". In this case, it's technically a bare mutlihash (it's a version 0 CID) but it could also look like `/ipfs/zb2rhiQSKuKxgXTQS8BkN7hRLoGBU3zJe7CShScajr8cVsdJ6` or even `/ipfs/bafkreifoybygix7fh3r3g5rqle3wcnhqldgdg4shzf4k3ulyw3gn7mabt4` (base32).

And to answer your question, at the moment you need to fetch the block the CID points to to determine what it is. In the future (unixfs v2), we'd like to add this information to directory entries for faster directory listings but we aren't there yet.
