### ISSUE TITLE
can i build this jar with jdk 1.7

### ISSUE THREAD

**Issue by onkarshedge** [ipfs/java-ipfs-api#9]
I changed the source and target in pom.xml from 1.8 to 1.7. the jar was created successfully. Will i face any issues using it ? @ianopolous

**Comment by ianopolous** [comment]
If it compiles to 1.7 then it should be fine. Let me know if it isn't.

**Comment by onkarshedge** [comment]
Using the jar gives me error. java.util.Optional is a feature of jdk 1.8

**Comment by ianopolous** [comment]
Ah yes, Optionals only arrived in 1.8. Are you unable to upgrade?
